# Generated by Django 4.2.4 on 2024-07-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactheader',
            name='header_description',
        ),
    ]
