# Generated by Django 4.2.4 on 2024-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='career_page')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CareerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('resume', models.FileField(upload_to='resumes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
