# Generated by Django 4.2.4 on 2024-07-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpage',
            name='description',
        ),
    ]
