# Generated by Django 4.2.4 on 2024-02-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlights_title', models.CharField(max_length=100)),
                ('highlights_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Highlight',
        ),
    ]
