# Generated by Django 4.2.4 on 2024-06-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_specialized',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
