
# Generated by Django 4.2.4 on 2024-07-04 08:36
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_service_is_specialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='order_by',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
