# Generated by Django 4.2.4 on 2024-04-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_alter_socialmedia_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homehighlights',
            name='highlights_description',
        ),
        migrations.RemoveField(
            model_name='homehighlights',
            name='highlights_title',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='achievement',
            name='achievements_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homehighlights',
            name='icon',
            field=models.ImageField(default=1, upload_to='homehighlights/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homehighlights',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='service_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievements_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievements_icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievements_icons/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievements_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
