# Generated by Django 5.0.1 on 2024-03-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_alter_socialmedia_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
