# Generated by Django 4.2.4 on 2024-07-05 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_achievement_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='order_by',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
