# Generated by Django 4.2.4 on 2024-04-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_remove_homehighlights_highlights_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='achievements_description',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='achievements_title',
        ),
    ]
