# Generated by Django 4.2.4 on 2024-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_remove_achievement_achievements_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
