# Generated by Django 4.2.4 on 2024-04-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0006_achievementsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievements_icon',
            field=models.ImageField(default=1, upload_to='achievements_icons/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievements_subtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
