# Generated by Django 4.2.4 on 2024-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0007_alter_achievement_achievements_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='homehighlights',
            old_name='title',
            new_name='sub_title',
        ),
    ]
