# Generated by Django 4.2.4 on 2024-04-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0008_highlightssection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
