# Generated by Django 4.2.4 on 2024-04-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0009_markettitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='short_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
