# Generated by Django 5.0.4 on 2024-05-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0011_ournetworktitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
