# Generated by Django 5.0.1 on 2024-03-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='key_diffrentiates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='key_diffrentiates/')),
                ('tagline', models.TextField()),
            ],
        ),
    ]
