# Generated by Django 5.0.1 on 2024-03-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key_diffrentiates',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='key_diffrentiates',
            name='title',
        ),
    ]
