# Generated by Django 4.2.4 on 2024-05-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0002_key_diffrentiatessection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_diffrentiatessection',
            name='subtitle',
            field=models.TextField(),
        ),
    ]
