# Generated by Django 4.2.4 on 2024-04-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_remove_homehighlights_highlights_description_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='related_service',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='title',
        ),
        migrations.CreateModel(
            name='Subheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('related_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.service')),
            ],
        ),
        migrations.AddField(
            model_name='subservice',
            name='related_heading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.subheading'),
            preserve_default=False,
        ),
    ]
