# Generated by Django 4.2.4 on 2024-04-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_subservice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='sub_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
