# Generated by Django 4.2.4 on 2024-05-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_specializedservice_specializedsubservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subheading',
            old_name='title',
            new_name='subheading',
        ),
    ]
