# Generated by Django 4.2.4 on 2024-02-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='BlogImage',
        ),
    ]
