# Generated by Django 4.2.4 on 2024-05-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_image_blogimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='blog_post',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='quotes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highlight',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
