# Generated by Django 4.2.4 on 2024-07-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogpost_description_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
