# Generated by Django 4.2.4 on 2024-05-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogpost_publish_date'),
        ('blogs', '0003_remove_quote_blog_post_blogpost_quotes_and_more'),
    ]

    operations = [
    ]
