# Generated by Django 5.0.4 on 2024-05-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_header_image', models.ImageField(upload_to='Location_header_image/')),
                ('location_title', models.CharField(max_length=100)),
                ('location_subtitle', models.TextField()),
                ('location_description', models.TextField()),
                ('alt_img_text', models.TextField(blank=True, max_length=300, null=True)),
                ('alt_img_title', models.TextField(blank=True, max_length=300, null=True)),
                ('alt_img_Caption', models.TextField(blank=True, max_length=300, null=True)),
                ('alt_img_description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTagsLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charset', models.CharField(blank=True, max_length=150, null=True)),
                ('viewport', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('keywords', models.CharField(blank=True, max_length=150, null=True)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('robots', models.CharField(blank=True, max_length=150, null=True)),
                ('copyright', models.CharField(blank=True, max_length=150, null=True)),
                ('referrer', models.CharField(blank=True, max_length=150, null=True)),
                ('og_title', models.CharField(blank=True, max_length=150, null=True)),
                ('og_type', models.CharField(blank=True, max_length=150, null=True)),
                ('og_url', models.CharField(blank=True, max_length=150, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='meta_tags_location/')),
                ('og_description', models.CharField(blank=True, max_length=150, null=True)),
                ('og_site_name', models.CharField(blank=True, max_length=150, null=True)),
                ('og_locale', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_card', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_site', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_title', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_description', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='meta_tags_location/')),
                ('twitter_image_alt', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=100)),
                ('phone_number1', models.CharField(max_length=20)),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('country_manager_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('country_manager_phone1', models.CharField(max_length=20)),
                ('country_manager_phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('country_manager_email', models.EmailField(max_length=254)),
                ('is_head_office', models.BooleanField(default=False)),
                ('office_url', models.URLField()),
                ('office_description', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialmedia.location')),
            ],
        ),
    ]
