# Generated by Django 4.2.4 on 2024-07-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_page', '0002_location_page_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='office_description',
        ),
        migrations.AlterField(
            model_name='office',
            name='office_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='office',
            name='place_name',
            field=models.TextField(),
        ),
    ]
