# Generated by Django 4.2.4 on 2024-04-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_page', '0002_location_page_alt_img_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='office_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='location_page',
            name='alt_img_Caption',
        ),
        migrations.RemoveField(
            model_name='location_page',
            name='alt_img_description',
        ),
        migrations.RemoveField(
            model_name='location_page',
            name='alt_img_text',
        ),
        migrations.RemoveField(
            model_name='location_page',
            name='alt_img_title',
        ),
        migrations.AddField(
            model_name='office',
            name='designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
