# Generated by Django 4.2.4 on 2024-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_page', '0003_remove_office_office_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='fax',
            field=models.CharField(default='', max_length=20),
        ),
    ]
