# Generated by Django 4.2.4 on 2024-04-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_page', '0003_office_location_remove_location_page_alt_img_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='place_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
