# Generated by Django 5.0.4 on 2024-05-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_page', '0004_office_place_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='office_location',
        ),
    ]
