# Generated by Django 5.0.4 on 2024-05-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_page', '0005_delete_office_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='office_desccription',
            new_name='office_description',
        ),
    ]
