# Generated by Django 5.0.4 on 2024-05-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='our_team/'),
            preserve_default=False,
        ),
    ]
