# Generated by Django 4.2.4 on 2024-02-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='alt_img_Caption',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='certifications',
            name='alt_img_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='certifications',
            name='alt_img_text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='certifications',
            name='alt_img_title',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagesection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
