# Generated by Django 5.0.1 on 2024-03-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_certifications_alt_img_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='description',
        ),
    ]
