# Generated by Django 4.2.4 on 2024-06-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_alter_ourteam_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='achievement1',
            new_name='achievements',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='achievement2',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='achievement3',
        ),
    ]
