# Generated by Django 5.0.1 on 2024-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_remove_certifications_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourteam',
            old_name='name',
            new_name='team_title',
        ),
        migrations.AddField(
            model_name='ourteam',
            name='team_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourteam',
            name='title_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
