# Generated by Django 4.2.4 on 2024-04-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_rename_name_ourteam_team_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagesection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='team_description',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='team_title',
        ),
        migrations.AddField(
            model_name='aboutpagesection',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
