# Generated by Django 4.2.4 on 2024-04-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_remove_aboutpagesection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
