# Generated by Django 4.2.4 on 2024-04-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_certifications_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='title',
        ),
    ]
