# Generated by Django 4.2.4 on 2024-03-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_ourteam_team_description_ourteam_team_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='team_description',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='team_title',
        ),
    ]
