# Generated by Django 4.2.4 on 2024-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_milestonetitle_ourteamtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonetitle',
            name='sub_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
