# Generated by Django 4.2.4 on 2024-04-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0009_milestonetitle_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeAreTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
