# Generated by Django 4.2.4 on 2024-04-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0010_whatwearetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='order_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
