# Generated by Django 4.2.4 on 2024-05-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0011_ourteam_order_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurstoryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
