# Generated by Django 4.2.4 on 2024-07-04 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_card', '0002_servicescard_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescard',
            name='order_by',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
