# Generated by Django 4.2.4 on 2024-05-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoosesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(max_length=100)),
                ('bg_image', models.ImageField(upload_to='Chooses_Section/')),
            ],
        ),
    ]
