# Generated by Django 5.0.4 on 2024-05-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeaderCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='Customcss_home')),
                ('sub_title', models.TextField()),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
