# Generated by Django 5.0.4 on 2024-05-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeheadercustom',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='homeheadercustom',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homeheadercustom',
            name='link',
        ),
        migrations.RemoveField(
            model_name='homeheadercustom',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='homeheadercustom',
            name='title',
        ),
    ]
