# Generated by Django 4.2.4 on 2024-05-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0002_auto_20240524_1824'),
    ]

    operations = [
    ]
