# Generated by Django 4.2.4 on 2024-05-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0002_specializedservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecializedService',
            new_name='SpecializedServiceCustom',
        ),
    ]
