# Generated by Django 5.0.4 on 2024-05-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0002_rename_description_homeheadercustom_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicecardsCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
