# Generated by Django 4.2.4 on 2024-05-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0003_rename_specializedservice_specializedservicecustom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecializedServiceCustom',
        ),
    ]
