# Generated by Django 4.2.4 on 2024-05-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0002_ournetworkdescriptioncustom'),
        ('customcss', '0003_marketupdatescustom'),
    ]

    operations = [
    ]
