# Generated by Django 4.2.4 on 2024-05-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0002_keydiffrentiatorscustom'),
        ('customcss', '0003_contactformcustom'),
    ]

    operations = [
    ]
