# Generated by Django 4.2.4 on 2024-05-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0003_marketupdatescustom'),
        ('customcss', '0003_ournetworkofficescustom'),
    ]

    operations = [
    ]
