# Generated by Django 4.2.4 on 2024-05-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0003_auto_20240524_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marketscustom',
            new_name='marketcustom',
        ),
    ]
