# Generated by Django 4.2.4 on 2024-05-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0003_servicecardscustom'),
        ('customcss', '0004_ourstorycustom'),
    ]

    operations = [
    ]
