# Generated by Django 4.2.4 on 2024-05-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0004_footercustom'),
        ('customcss', '0005_acheievementcustom'),
    ]

    operations = [
    ]
