# Generated by Django 4.2.4 on 2024-05-25 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0005_industriesheadercustom'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustriesBlocksCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customcss.industriesheadercustom')),
            ],
        ),
    ]
