# Generated by Django 4.2.4 on 2024-05-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customcss', '0006_milestonecustom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ournetworkCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
