# Generated by Django 4.2.4 on 2023-10-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industriespage',
            name='alt_img_Caption',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='industriespage',
            name='alt_img_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='industriespage',
            name='alt_img_text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='industriespage',
            name='alt_img_title',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
