# Generated by Django 4.2.4 on 2024-06-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industriespage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
