# Generated by Django 5.0.4 on 2024-05-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeheader',
            name='alt_img_Caption',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homeheader',
            name='alt_img_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homeheader',
            name='alt_img_text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homeheader',
            name='alt_img_title',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
