# Generated by Django 4.2.4 on 2024-04-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeheader',
            name='alt_img_Caption',
        ),
        migrations.RemoveField(
            model_name='homeheader',
            name='alt_img_description',
        ),
        migrations.RemoveField(
            model_name='homeheader',
            name='alt_img_text',
        ),
        migrations.RemoveField(
            model_name='homeheader',
            name='alt_img_title',
        ),
        migrations.AddField(
            model_name='homeheader',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
