# Generated by Django 4.2.4 on 2024-07-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeheader',
            name='slug',
        ),
    ]
