# Generated by Django 5.0.4 on 2024-05-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrycard',
            name='description',
            field=models.TextField(),
        ),
    ]
