# Generated by Django 4.2.4 on 2024-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='icon',
            field=models.ImageField(upload_to='AppFooter/'),
        ),
    ]
